#' Repetability of panelists descriptions studied by confidence ellipses around
#' products per session
#' 
#' Virtual panels are generated using Boostrap techniques in order to display
#' confidence ellipses around products.
#' 
#' panellipse.session, step by step:\cr Step 1 Construct a data frame by
#' session \cr Step 2 Performs a selection of discriminating descriptors with
#' respect to a threshold set by users \cr Step 3 MFA is computed with one
#' group for one session \cr Step 4 Virtual panels are generated using Boostrap
#' techniques; the number of panels as well as their size are set by users with
#' the \emph{nbsimul} and \emph{nbchoix} parameters \cr Step 5 Coordinates of
#' the products with respect to each virtual panels are computed \cr Step 6
#' Each product is then circled by its confidence ellipse generated by virtual
#' panels and comprising (1-alpha)*100 percent of the virtual products
#' 
#' @param donnee a data frame made up of at least two qualitative variables
#' (\emph{product}, \emph{panelist}) and a set of quantitative variables
#' (sensory descriptors)
#' @param col.p the position of the \emph{product} variable
#' @param col.j the position of the \emph{panelist} variable
#' @param col.s the position of the \emph{session} variable
#' @param firstvar the position of the first sensory descriptor
#' @param lastvar the position of the last sensory descriptor (by default the
#' last column of \code{donnee})
#' @param alpha the confidence level of the ellipses
#' @param coord a length 2 vector specifying the components to plot
#' @param scale.unit boolean, if T the descriptors are scaled to unit variance
#' @param nbsimul the number of simulations (corresponding to the number of
#' virtual panels) used to compute the ellipses
#' @param nbchoix the number of panelists forming a virtual panel, by default
#' the number of panelists in the original panel
#' @param level.search.desc the threshold above which a descriptor is not
#' considered as discriminant according to AOV model
#' \code{"descriptor=Product+Panelist"}
#' @param centerbypanelist boolean, if T center the data by panelist before the
#' construction of the axes
#' @param scalebypanelist boolean, if T scale the data by panelist before the
#' construction of the axes (by default, FALSE is assigned to that parameter)
#' @param name.panelist boolean, if T then the name of each panelist is
#' displayed on the \code{plotpanelist} graph (by default, FALSE is assigned to
#' that parameter)
#' @param variability.variable boolean, if T a plot with the variability of the
#' variable is drawn and a confidence intervals of the correlations between
#' descriptors are calculated
#' @param cex cf. function \code{\link{par}} in the \pkg{graphics} package
#' @param color a vector with the colors used; by default there are 35 colors
#' defined
#' @return A list containing the following elements: \item{bysession}{the data
#' by session} \item{eig}{a matrix with the component of the factor analysis
#' (in row) and the eigenvalues, the inertia and the cumulative inertia for
#' each component} \item{coordinates}{a list with: the coordinates of the
#' products with respect to the panel and to each panelists and the coordinates
#' of the \emph{partial} products with respect to the panel and to each
#' panelists} \item{hotelling}{returns a matrix with the P-values of the
#' Hotelling's T2 tests for each pair of products: this matrix allows to find
#' the product which are significatnly different for the 2-components sensory
#' description} \item{variability}{returns an index of the sessions'
#' reproductibility: the first eigenvalue of the separate PCA performed on
#' homologous descriptors}
#' 
#' Returns a graph of the products as well as a correlation circle of the
#' descriptors.\cr
#' 
#' Returns a graph where each product is displayed with respect to a panel and
#' to each panelist composing the panel; products described by the panel are
#' displayed as square, they are displayed as circle when they are described by
#' each panelist.\cr
#' 
#' Returns a graph where each product is circled by its confidence ellipse
#' generated by virtual panels.\cr
#' 
#' Returns a graph where each partial product is circled by its confidence
#' ellipse generated by virtual panels.\cr
#' 
#' Returns a graph where the variability of each variable is drawn on the
#' correlation circle graph. \cr
#' @author F Husson, S Le
#' @seealso \code{\link{panellipse}}
#' @references Husson F., Le Dien S. & Pages J.  (2005). Confidence ellipse for
#' the sensory profiles obtained by Principal Components Analysis. \emph{Food
#' Quality and Preference}.  16 (3), 245-250. \cr Pages J. & Husson F. (2005).
#' Multiple Factor Analysis with confidence ellipses: a methodology to study
#' the relationships between sensory and instrumental data. To be published in
#' \emph{Journal of Chemometrics}. \cr Husson F., Le S. & Pages J.  Variability
#' of the representation of the variables resulting from PCA in the case of a
#' conventional sensory profile. \emph{Food Quality and Preference}.  16 (3),
#' 245-250.
#' @keywords multivariate
#' @examples
#' 
#' \dontrun{
#' data(chocolates)
#' res <- panellipse.session(sensochoc, col.p = 4, col.j = 1, col.s = 2, 
#'     firstvar = 5)
#' magicsort(res$variability)
#' for (i in 1:dim(res$hotelling$bysession)[3]) coltable(res$hotelling$bysession[,,i], 
#'     main.title = paste("P-values for the Hotelling's T2 tests (",
#'     dimnames(res$hotelling$bysession)[3][[1]][i],")",sep=""))
#' }
#' 
#' @export panellipse.session
"panellipse.session" <- function(donnee,col.p,col.j,col.s,firstvar,lastvar=ncol(donnee),alpha=0.05,coord=c(1,2),scale.unit=TRUE,nbsimul=500,nbchoix=NULL,level.search.desc=0.2,centerbypanelist=TRUE,scalebypanelist=FALSE,name.panelist=FALSE,variability.variable=FALSE,cex=1,color=NULL){

hotelling <- function(d1,d2,n1=nrow(d1),n2=nrow(d2)){
    k <- ncol(d1)
#    n1 <- nrow(d1)
#    n2 <- nrow(d2)
    xbar1 <- apply(d1,2,mean)
    xbar2 <- apply(d2,2,mean)
    dbar <- xbar2-xbar1
    v <- ((n1-1)*var(d1)+(n2-1)*var(d2))/(n1+n2-2)
    t2 <- n1*n2*dbar%*%solve(v)%*%dbar/(n1+n2)
    f <- (n1+n2-k-1)*t2/((n1+n2-2)*k)
    return(pf(f,k,n1+n2-k-1,lower.tail=FALSE))
}

if (length(color)==0) color = c("black","red","green3","blue",
  "cyan","magenta","darkgray","darkgoldenrod","darkgreen","violet","turquoise","orange","lightpink","lavender","yellow","lightgreen","lightgrey",
  "lightblue","darkkhaki", "darkmagenta","darkolivegreen","lightcyan", "darkorange",
  "darkorchid","darkred","darksalmon","darkseagreen","darkslateblue","darkslategray","darkslategrey",
  "darkturquoise","darkviolet", "lightgray","lightsalmon","lightyellow", "maroon")
for (j in 1:(firstvar-1)) donnee[,j]=as.factor(donnee[,j])
labseance=levels(as.factor(donnee[,col.s]))
nbseance <- length(labseance)
labprod = levels(as.factor(donnee[,col.p]))
nbprod <- length(levels(donnee[,col.p]))
nbjuge <- length(levels(donnee[,col.j]))

  donnee <- search.desc(donnee,col.j=col.j,col.p=col.p,firstvar=firstvar,lastvar=lastvar,level=level.search.desc)
  if (nbseance <2) print("This procedure is not adapted, there is only one session")
  oo=order(donnee[,col.j])
  donnee<- donnee[oo,]
  oo=order(donnee[,col.p])
  donnee<- donnee[oo,]
  oo=order(donnee[,col.s])
  donnee<- donnee[oo,]

  don <- cbind.data.frame(donnee[donnee[,col.s]==labseance[1],col.j],donnee[donnee[,col.s]==labseance[1],col.p])

  for (seance in 1:nbseance)  don <- cbind.data.frame(don,data.frame(donnee[donnee[,col.s]==labseance[seance],firstvar:ncol(donnee)],row.names=paste(donnee[donnee[,col.s]==labseance[seance],col.p],donnee[donnee[,col.s]==labseance[seance],col.j],sep=".")))
  colnames(don) <- colnames(donnee)[c(col.j,col.p,rep(firstvar:ncol(donnee),nbseance))]
  colnames(don) <- paste(colnames(don),c("","",rep(paste(".S",1:nbseance,sep=""),rep(ncol(donnee)-firstvar+1,nbseance))),sep="")
  bb=panellipse(don,group=c(rep(ncol(donnee)-firstvar+1,nbseance)),name.group=c(paste("S",1:nbseance,sep="")),col.j=1,col.p=2,firstvar=3,alpha=alpha,coord=coord,scale.unit=scale.unit,nbsimul=nbsimul,nbchoix=nbchoix,level.search.desc=1,centerbypanelist=centerbypanelist,scalebypanelist=scalebypanelist,name.panelist=name.panelist,variability.variable=variability.variable,cex=cex,color=color)
  legend("bottomleft",legend=paste(colnames(donnee)[col.s],1:nbseance,sep=" "),lty=1:nbseance,cex=0.8,bg="white")

  mat = list(bysession=bb$hotelling$bygroup,byproduct=bb$hotelling$byproduct)
  dimnames(mat$bysession)=list(labprod,labprod,c(paste(colnames(donnee)[col.s],1:nbseance,sep=" "),"global"))
  dimnames(mat$byproduct)=list(paste(colnames(donnee)[col.s],1:nbseance,sep=" "),paste(colnames(donnee)[col.s],1:nbseance,sep=" "),labprod)

  aa <- matrix(0,ncol(donnee)-firstvar+1,2)
  res.average=averagetable(don,formul=as.formula(paste("~",colnames(don)[2])),firstvar=3)
  for (j in 1:(ncol(donnee)-firstvar+1)) aa[j,] <- as.matrix(PCA(res.average[,(ncol(donnee)-firstvar+1)*(0:(nbseance-1))+j],graph=FALSE)$eig[1,1:2])
  rownames(aa) <- colnames(donnee[,firstvar:ncol(donnee)])
  colnames(aa) <- c("eig1","Reproductibility")
  res <- list()
  res$bysession =don
  res$eig =bb$eig
  res$coordinates =bb$coordinates
  if (variability.variable) res$correl =bb$correl
  res$hotelling =mat
  res$variability=aa
  return(res)
}
